project:
  type: website

website:
  title: "test-website"
  sidebar:
    style: "docked"
    contents:
      - section: "Pages"
        contents:
          - href: index.qmd
          - href: slides.qmd
